"""empty message

Revision ID: 205a8d2d7657
Revises: 8d421279199a
Create Date: 2019-11-26 21:55:32.231742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205a8d2d7657'
down_revision = '8d421279199a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'excerpt_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('excerpt_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
